import { useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { Ionicons } from '@expo/vector-icons';
import { ErrorCard, GradientButton, ScreenHeader } from '../components/ui';
import { colors, radius, shadow } from '../theme';
import { getVisualIntentSuggestions } from '../services/api';

export default function Camera(){const router=useRouter();const [uri,setUri]=useState('');const [base64,setBase64]=useState('');const [suggestions,setSuggestions]=useState<string[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const choose=async(camera:boolean)=>{setError('');const permission=camera?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){setError(`Please allow ${camera?'camera':'photo library'} access in your device settings.`);return}const result=camera?await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.55,base64:true}):await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.55,base64:true});if(!result.canceled){setUri(result.assets[0].uri);setBase64(result.assets[0].base64??'');setSuggestions([])}};const analyze=async()=>{if(!base64){setError('This photo could not be prepared. Please choose another.');return}setLoading(true);setError('');try{setSuggestions(await getVisualIntentSuggestions(base64))}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setLoading(false)}};return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="Camera Assist" onBack={()=>router.back()}/><Text style={styles.title}>Show what you mean.</Text><Text style={styles.copy}>Take or choose a photo. ReVoice will suggest possible things you may want to say.</Text><View style={styles.preview}>{uri?<Image source={{uri}} style={styles.image}/>:<><View style={styles.cameraIcon}><Ionicons name="camera" size={38} color={colors.primary}/></View><Text style={styles.previewTitle}>No photo selected</Text><Text style={styles.previewCopy}>Photos are analyzed temporarily and are not saved by ReVoice.</Text></>}</View><View style={styles.row}><Pressable onPress={()=>choose(true)} style={styles.secondary}><Ionicons name="camera-outline" size={21} color={colors.text}/><Text style={styles.secondaryText}>Take photo</Text></Pressable><Pressable onPress={()=>choose(false)} style={styles.secondary}><Ionicons name="images-outline" size={21} color={colors.text}/><Text style={styles.secondaryText}>Choose photo</Text></Pressable></View>{uri&&<GradientButton title="Find possible phrases" onPress={analyze} loading={loading} style={{marginTop:14}}/>}{error&&<View style={{marginTop:16}}><ErrorCard message={error}/></View>}{suggestions.length>0&&<><Text style={styles.heading}>Possible phrases</Text>{suggestions.map(s=><Pressable key={s} onPress={()=>router.push({pathname:'/speak',params:{text:s}})} style={styles.suggestion}><Text style={styles.suggestionText}>{s}</Text><Ionicons name="play-circle" size={36} color="#2867FA"/></Pressable>)}</>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:22,paddingBottom:40},title:{fontFamily:'Jakarta-ExtraBold',fontSize:30,color:colors.text,marginTop:14},copy:{fontFamily:'Jakarta-Regular',fontSize:14,lineHeight:21,color:colors.muted,marginTop:7,marginBottom:20},preview:{height:290,borderRadius:radius.lg,backgroundColor:'#EDF4FF',borderWidth:1,borderColor:'#D9E7FF',overflow:'hidden',alignItems:'center',justifyContent:'center',padding:28},image:{width:'100%',height:'100%',resizeMode:'cover'},cameraIcon:{width:72,height:72,borderRadius:36,backgroundColor:'white',alignItems:'center',justifyContent:'center',marginBottom:14},previewTitle:{fontFamily:'Jakarta-Bold',fontSize:17,color:colors.text},previewCopy:{fontFamily:'Jakarta-Regular',fontSize:12,lineHeight:18,color:colors.muted,textAlign:'center',marginTop:6},row:{flexDirection:'row',gap:10,marginTop:13},secondary:{flex:1,minHeight:54,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},secondaryText:{fontFamily:'Jakarta-SemiBold',fontSize:13,color:colors.text},heading:{fontFamily:'Jakarta-Bold',fontSize:17,color:colors.text,marginTop:24,marginBottom:10},suggestion:{minHeight:72,padding:14,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:12,marginBottom:10,...shadow},suggestionText:{flex:1,fontFamily:'Jakarta-Medium',fontSize:14,lineHeight:20,color:colors.text}});
