import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { BottomNav, ScreenHeader } from '../components/ui';
import { colors, radius } from '../theme';
import { HistoryItem } from '../types';
import { getHistory, setHistory } from '../services/storage';

export default function History(){const router=useRouter();const [items,setItems]=useState<HistoryItem[]>([]);useFocusEffect(useCallback(()=>{getHistory().then(setItems)},[]));const update=async(next:HistoryItem[])=>{setItems(next);await setHistory(next)};return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="History" onBack={()=>router.replace('/home')}/>{items.length===0?<View style={styles.empty}><Ionicons name="chatbubbles-outline" size={56} color={colors.primary}/><Text style={styles.emptyTitle}>Your voice history</Text><Text style={styles.emptyCopy}>Phrases you choose to speak will appear here, stored only on this device.</Text></View>:items.map(item=><View key={item.id} style={styles.card}><Pressable style={{flex:1}} onPress={()=>router.push({pathname:'/speak',params:{text:item.text}})}><Text style={styles.text}>{item.text}</Text><Text style={styles.date}>{new Date(item.createdAt).toLocaleDateString()}</Text></Pressable><Pressable hitSlop={10} onPress={()=>update(items.map(x=>x.id===item.id?{...x,favorite:!x.favorite}:x))}><Ionicons name={item.favorite?'heart':'heart-outline'} size={24} color={item.favorite?colors.coral:colors.muted}/></Pressable><Pressable hitSlop={10} onPress={()=>update(items.filter(x=>x.id!==item.id))}><Ionicons name="trash-outline" size={22} color={colors.muted}/></Pressable></View>)}</ScrollView><BottomNav active="History" /></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:22,paddingBottom:40},empty:{alignItems:'center',paddingTop:120,paddingHorizontal:25},emptyTitle:{fontFamily:'Jakarta-Bold',fontSize:21,color:colors.text,marginTop:16},emptyCopy:{fontFamily:'Jakarta-Regular',fontSize:14,lineHeight:21,color:colors.muted,textAlign:'center',marginTop:7},card:{minHeight:84,padding:16,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:14,marginTop:11},text:{fontFamily:'Jakarta-SemiBold',fontSize:14,lineHeight:20,color:colors.text},date:{fontFamily:'Jakarta-Regular',fontSize:11,color:colors.muted,marginTop:5}});
