import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Brand, GradientButton } from '../components/ui';
import { colors, radius, shadow } from '../theme';

const quick = [ ['water','Water','I would like some water.'], ['restaurant','Food','I would like something to eat.'], ['business','Bathroom','I need to use the bathroom.'], ['flash','Pain',"I'm in pain."], ['bed','Rest','I need to rest.'], ['person','Call someone','Please call someone for me.'] ] as const;
export default function Home() { const router = useRouter(); const openSpeak = (text: string) => router.push({ pathname: '/speak', params: { text } }); return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Brand /><Pressable onPress={() => router.push('/settings')} hitSlop={12}><Ionicons name="settings-outline" size={26} color={colors.muted} /></Pressable></View><Text style={styles.title}>What do you{`\n`}want to say?</Text><Text style={styles.copy}>Tap, type, take a photo, or use quick buttons.{`\n`}We'll suggest phrases you can speak.</Text><GradientButton title="Help me say something" onPress={() => router.push('/intent')} /><View style={styles.sectionRow}><Text style={styles.section}>Quick Speak</Text><Pressable onPress={() => router.push('/camera')}><Text style={styles.camera}>Camera Assist  →</Text></Pressable></View><View style={styles.grid}>{quick.map(([icon,label,text]) => <Pressable key={label} accessibilityRole="button" accessibilityLabel={label} onPress={() => openSpeak(text)} style={({pressed}) => [styles.quick, pressed && styles.pressed]}><Ionicons name={icon} size={29} color={label === 'Pain' ? '#FF9E2C' : label === 'Rest' ? colors.purple : colors.primary} /><Text style={styles.quickText}>{label}</Text></Pressable>)}</View><View style={styles.binary}><Pressable onPress={() => openSpeak('Yes.')} style={[styles.binaryCard, styles.yes]}><Ionicons name="checkmark-circle" size={38} color={colors.mint} /><Text style={styles.binaryText}>Yes</Text></Pressable><Pressable onPress={() => openSpeak('No.')} style={[styles.binaryCard, styles.no]}><Ionicons name="close-circle" size={38} color={colors.danger} /><Text style={styles.binaryText}>No</Text></Pressable></View></ScrollView><View style={styles.nav}>{[['home','Home','/home'],['time-outline','History','/history'],['person-outline','Profile','/profile']].map(([icon,label,path]) => <Pressable key={label} onPress={() => router.replace(path as never)} style={styles.navItem}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={24} color={label === 'Home' ? '#2867FA' : colors.muted} /><Text style={[styles.navText,label === 'Home' && {color:'#2867FA'}]}>{label}</Text></Pressable>)}</View></SafeAreaView>; }
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:colors.background},content:{padding:22,paddingBottom:22},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:22},title:{fontFamily:'Jakarta-ExtraBold',fontSize:34,lineHeight:40,color:colors.text,letterSpacing:-1.2},copy:{fontFamily:'Jakarta-Regular',fontSize:14,lineHeight:21,color:colors.muted,marginTop:8,marginBottom:20},sectionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:25,marginBottom:12},section:{fontFamily:'Jakarta-Bold',fontSize:17,color:colors.text},camera:{fontFamily:'Jakarta-SemiBold',fontSize:13,color:colors.primary},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},quick:{width:'31%',minHeight:88,backgroundColor:colors.surface,borderRadius:radius.md,alignItems:'center',justifyContent:'center',gap:7,borderWidth:1,borderColor:'#EEF1F6',...shadow},pressed:{transform:[{scale:.97}],backgroundColor:colors.paleBlue},quickText:{fontFamily:'Jakarta-SemiBold',fontSize:12,color:colors.text,textAlign:'center'},binary:{flexDirection:'row',gap:12,marginTop:14},binaryCard:{flex:1,minHeight:94,borderRadius:radius.md,alignItems:'center',justifyContent:'center',gap:5},yes:{backgroundColor:'#EAFBF7'},no:{backgroundColor:'#FFF0F3'},binaryText:{fontFamily:'Jakarta-SemiBold',fontSize:14,color:colors.text},nav:{height:72,borderTopWidth:1,borderColor:colors.border,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',justifyContent:'space-around'},navItem:{minWidth:72,alignItems:'center',gap:3},navText:{fontFamily:'Jakarta-Medium',fontSize:11,color:colors.muted} });
