import { Image, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { Brand, GradientButton } from '../components/ui';
import { colors } from '../theme';
import { completeOnboarding } from '../services/storage';

export default function Onboarding() { const router = useRouter(); const start = async () => { await completeOnboarding(); router.replace('/home'); }; return <SafeAreaView style={styles.safe}><View style={styles.top}><Brand /><Text style={styles.skip} onPress={start}>Skip</Text></View><View style={styles.content}><Text style={styles.title}>Turn intent{`\n`}into <Text style={styles.blue}>voice.</Text></Text><Text style={styles.copy}>A simpler way to communicate{`\n`}what matters.</Text><Image source={require('../assets/branding/revoice-symbol-transparent.png')} resizeMode="contain" style={styles.hero} /><LinearGradient colors={['transparent', '#DCEAFF']} style={styles.glow} /></View><GradientButton title="Get started" icon="arrow-forward" onPress={start} /><View style={styles.dots}><View style={styles.dotActive} /><View style={styles.dot} /><View style={styles.dot} /></View></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, padding: 24, backgroundColor: colors.background }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, skip: { fontFamily: 'Jakarta-Medium', color: colors.muted, fontSize: 15 }, content: { flex: 1, paddingTop: 72, overflow: 'hidden' }, title: { fontFamily: 'Jakarta-ExtraBold', fontSize: 42, lineHeight: 49, color: colors.text, letterSpacing: -1.5 }, blue: { color: '#3D6BEE' }, copy: { marginTop: 18, fontFamily: 'Jakarta-Regular', fontSize: 17, lineHeight: 26, color: colors.muted }, hero: { position: 'absolute', width: 330, height: 330, bottom: 0, right: -92, zIndex: 2 }, glow: { position: 'absolute', height: 230, left: -30, right: -30, bottom: -20, borderRadius: 150 }, dots: { flexDirection: 'row', justifyContent: 'center', gap: 10, paddingVertical: 22 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#D5DEED' }, dotActive: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.primary } });
