import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { PurchasesPackage } from 'react-native-purchases';
import { GradientButton, ScreenHeader } from '../components/ui';
import { colors, radius } from '../theme';
import { getOfferings, purchasePackage, restorePurchases } from '../services/revenuecat';

const features=[['sparkles','AI Intent Builder'],['camera','Camera Assist'],['people','Multiple Care Profiles'],['time','Conversation History'],['heart','Personalized communication context']] as const;
export default function Premium(){const router=useRouter();const [packages,setPackages]=useState<PurchasesPackage[]>([]);const [selected,setSelected]=useState(0);const [loading,setLoading]=useState(false);const [unlocked,setUnlocked]=useState(false);useEffect(()=>{getOfferings().then(o=>setPackages(o?.availablePackages??[])).catch(()=>{})},[]);const buy=async()=>{if(!packages[selected]){Alert.alert('Development build required','Add your RevenueCat public SDK key and open ReVoice in an EAS Development Build to test a real purchase.');return}setLoading(true);try{setUnlocked(await purchasePackage(packages[selected]))}catch(e:any){if(!e?.userCancelled)Alert.alert('Purchase unavailable','Please try again in a moment.')}finally{setLoading(false)}};const restore=async()=>{try{setUnlocked(await restorePurchases())}catch{Alert.alert('Restore unavailable','Please try again in a moment.')}};return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><ScreenHeader onBack={()=>router.back()}/><View style={styles.badge}><Ionicons name="diamond" size={16} color={colors.purple}/><Text style={styles.badgeText}>ReVoice+</Text></View><Text style={styles.title}>{unlocked?'ReVoice+ unlocked':'Unlock more possibilities.'}</Text>{unlocked?<View style={styles.success}><Ionicons name="checkmark-circle" size={64} color={colors.mint}/><Text style={styles.successTitle}>You're all set.</Text><Text style={styles.successCopy}>Premium communication tools are now available.</Text></View>:<>{features.map(([icon,label])=><View key={label} style={styles.feature}><Ionicons name={icon} size={21} color={colors.purple}/><Text style={styles.featureText}>{label}</Text></View>)}<View style={{marginTop:20}}>{packages.length?packages.map((pkg,i)=><Pressable key={pkg.identifier} onPress={()=>setSelected(i)} style={[styles.plan,selected===i&&styles.planSelected]}><Ionicons name={selected===i?'radio-button-on':'radio-button-off'} size={22} color={selected===i?'#2867FA':colors.muted}/><View><Text style={styles.planTitle}>{pkg.product.title}</Text><Text style={styles.planPrice}>{pkg.product.priceString}</Text></View></Pressable>):<><View style={[styles.plan,styles.planSelected]}><Ionicons name="radio-button-on" size={22} color="#2867FA"/><View><Text style={styles.planTitle}>Monthly</Text><Text style={styles.planPrice}>Connect RevenueCat to load the current price</Text></View></View><View style={styles.plan}><Ionicons name="radio-button-off" size={22} color={colors.muted}/><View><Text style={styles.planTitle}>Yearly</Text><Text style={styles.planPrice}>Best value</Text></View></View></>}</View><GradientButton title="Start ReVoice+" icon="diamond" onPress={buy} loading={loading} style={{marginTop:14}}/><Pressable onPress={restore}><Text style={styles.restore}>Restore purchases</Text></Pressable></>}<Text style={styles.footer}>Communication essentials — Quick Speak, Yes/No, basic phrases and device voice — are always free.</Text></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:22,paddingBottom:35},badge:{alignSelf:'center',paddingVertical:7,paddingHorizontal:12,borderRadius:99,backgroundColor:'#F1E9FF',flexDirection:'row',alignItems:'center',gap:6,marginTop:8},badgeText:{fontFamily:'Jakarta-Bold',fontSize:15,color:colors.purple},title:{fontFamily:'Jakarta-ExtraBold',fontSize:34,lineHeight:41,color:colors.text,textAlign:'center',marginTop:22,marginBottom:25,letterSpacing:-1.2},feature:{flexDirection:'row',alignItems:'center',gap:13,minHeight:42,paddingHorizontal:12},featureText:{fontFamily:'Jakarta-Medium',fontSize:15,color:colors.text},plan:{minHeight:70,padding:14,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',gap:12,marginBottom:9},planSelected:{borderColor:'#2867FA',backgroundColor:'#F4F7FF'},planTitle:{fontFamily:'Jakarta-SemiBold',fontSize:14,color:colors.text},planPrice:{fontFamily:'Jakarta-Regular',fontSize:11,color:colors.muted,marginTop:3},restore:{fontFamily:'Jakarta-SemiBold',fontSize:13,color:colors.primary,textAlign:'center',padding:16},footer:{fontFamily:'Jakarta-Regular',fontSize:11,lineHeight:17,color:colors.muted,textAlign:'center',marginTop:14,paddingHorizontal:12},success:{alignItems:'center',backgroundColor:'#ECFBF7',borderRadius:radius.lg,padding:32},successTitle:{fontFamily:'Jakarta-Bold',fontSize:22,color:colors.text,marginTop:12},successCopy:{fontFamily:'Jakarta-Regular',fontSize:13,color:colors.muted,textAlign:'center',marginTop:6}});
