import { StyleSheet, Text, View, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { ScreenHeader } from '../components/ui';
import { colors, radius } from '../theme';

const sections=[['people','People','Ana · Daughter'],['location','Places','Home · Park · University'],['time','Routine','Morning · Afternoon'],['options','Preferences','Clear and concise language']] as const;
export default function Profile(){const router=useRouter();return <SafeAreaView style={styles.safe}><View style={styles.content}><ScreenHeader title="Care Profile" onBack={()=>router.replace('/home')}/><Text style={styles.title}>Context that helps.</Text><Text style={styles.copy}>Personal details can improve suggestions. For this MVP, everything stays on this device.</Text>{sections.map(([icon,title,value])=><Pressable key={title} style={styles.card}><View style={styles.icon}><Ionicons name={icon} size={22} color="#2867FA"/></View><View style={{flex:1}}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.cardValue}>{value}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable>)}<Pressable onPress={()=>router.push('/premium')} style={styles.pro}><Ionicons name="diamond" size={26} color={colors.purple}/><View style={{flex:1}}><Text style={styles.proTitle}>ReVoice+</Text><Text style={styles.proCopy}>Unlock richer personal context.</Text></View><Ionicons name="arrow-forward" size={21} color={colors.purple}/></Pressable></View></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:22},title:{fontFamily:'Jakarta-ExtraBold',fontSize:30,color:colors.text,marginTop:15},copy:{fontFamily:'Jakarta-Regular',fontSize:14,lineHeight:21,color:colors.muted,marginTop:7,marginBottom:20},card:{minHeight:78,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:14,flexDirection:'row',alignItems:'center',gap:13,marginBottom:10},icon:{width:44,height:44,borderRadius:15,backgroundColor:'#EDF4FF',alignItems:'center',justifyContent:'center'},cardTitle:{fontFamily:'Jakarta-SemiBold',fontSize:15,color:colors.text},cardValue:{fontFamily:'Jakarta-Regular',fontSize:12,color:colors.muted,marginTop:3},pro:{marginTop:12,minHeight:82,padding:16,borderRadius:radius.md,backgroundColor:'#F4EDFF',borderWidth:1,borderColor:'#DDC9FF',flexDirection:'row',alignItems:'center',gap:13},proTitle:{fontFamily:'Jakarta-Bold',fontSize:16,color:colors.purple},proCopy:{fontFamily:'Jakarta-Regular',fontSize:12,color:colors.muted,marginTop:3}});
