import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { BottomNav, ScreenHeader } from '../components/ui';
import { colors, radius } from '../theme';
import { useAppSettings } from '../context/app-settings';

export default function Settings(){const router=useRouter();const {settings,updateSettings}=useAppSettings();const dark=settings.darkMode;return <SafeAreaView style={[styles.safe,dark&&styles.safeDark]}><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="Settings" onBack={()=>router.replace('/home')}/><Text style={[styles.section,dark&&styles.textDark]}>Voice & appearance</Text><SettingSwitch icon="moon-outline" title="Dark mode" description="Use a darker, low-glare appearance" value={dark} onValueChange={value=>updateSettings({darkMode:value})} dark={dark}/><SettingSwitch icon="speedometer-outline" title="Slower voice by default" description="Start spoken phrases 25% slower" value={settings.defaultSlower} onValueChange={value=>updateSettings({defaultSlower:value})} dark={dark}/><Text style={[styles.section,dark&&styles.textDark]}>Account & help</Text><Pressable onPress={()=>router.push('/premium')} style={[styles.row,dark&&styles.rowDark]}><Ionicons name="diamond-outline" size={23} color={colors.purple}/><View style={styles.rowContent}><Text style={[styles.rowText,dark&&styles.textDark]}>ReVoice+</Text><Text style={styles.rowDescription}>Plans, premium tools and restore purchases</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable><Pressable onPress={()=>router.push('/onboarding')} style={[styles.row,dark&&styles.rowDark]}><Ionicons name="play-circle-outline" size={23} color={colors.primary}/><View style={styles.rowContent}><Text style={[styles.rowText,dark&&styles.textDark]}>Replay onboarding</Text><Text style={styles.rowDescription}>View the introduction without deleting your data</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable><View style={[styles.about,dark&&styles.rowDark]}><Text style={[styles.title,dark&&styles.textDark]}>About & Safety</Text><Text style={styles.copy}>ReVoice is an assistive communication tool. It does not diagnose, treat, or provide medical advice and is not a substitute for professional care or emergency services.</Text><Text style={styles.principle}>Human Intent → AI Assistance → Human Choice → Voice</Text></View></ScrollView><BottomNav active="Settings" /></SafeAreaView>}

function SettingSwitch({icon,title,description,value,onValueChange,dark}:{icon:keyof typeof Ionicons.glyphMap;title:string;description:string;value:boolean;onValueChange:(value:boolean)=>void;dark:boolean}){return <View style={[styles.row,dark&&styles.rowDark]}><Ionicons name={icon} size={23} color={value?colors.primary:colors.muted}/><View style={styles.rowContent}><Text style={[styles.rowText,dark&&styles.textDark]}>{title}</Text><Text style={styles.rowDescription}>{description}</Text></View><Switch value={value} onValueChange={onValueChange} trackColor={{false:'#CBD5E1',true:'#8BB4FF'}} thumbColor={value?'#2867FA':'#F8FAFC'}/></View>}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},safeDark:{backgroundColor:'#071022'},content:{flexGrow:1,padding:22,paddingBottom:30},section:{fontFamily:'Jakarta-Bold',fontSize:13,color:colors.text,marginTop:18,marginBottom:-5,textTransform:'uppercase',letterSpacing:.5},row:{minHeight:72,padding:15,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:12,marginTop:12},rowDark:{backgroundColor:'#111C33',borderColor:'#263653'},rowContent:{flex:1},rowText:{fontFamily:'Jakarta-SemiBold',fontSize:15,color:colors.text},textDark:{color:'#F8FAFF'},rowDescription:{fontFamily:'Jakarta-Regular',fontSize:11,lineHeight:16,color:'#8493AC',marginTop:3},about:{marginTop:18,padding:20,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},title:{fontFamily:'Jakarta-Bold',fontSize:18,color:colors.text},copy:{fontFamily:'Jakarta-Regular',fontSize:13,lineHeight:21,color:colors.muted,marginTop:9},principle:{fontFamily:'Jakarta-SemiBold',fontSize:12,lineHeight:19,color:colors.primary,marginTop:16}});
