import { useEffect, useState } from 'react';
import { Animated, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { ScreenHeader } from '../components/ui';
import { colors, shadow } from '../theme';
import { speak, stopSpeaking } from '../services/speech';

export default function Speak() {
  const router = useRouter();
  const { text } = useLocalSearchParams<{ text: string }>();
  const phrase = Array.isArray(text) ? text[0] : text || 'Ready to speak.';
  const [speaking, setSpeaking] = useState(false);
  const [slower, setSlower] = useState(false);
  const [favorite, setFavorite] = useState(false);
  const [pulse] = useState(() => new Animated.Value(1));

  useEffect(() => () => { stopSpeaking(); }, []);
  useEffect(() => {
    if (speaking) {
      Animated.loop(Animated.sequence([
        Animated.timing(pulse, { toValue: 1.14, duration: 650, useNativeDriver: true }),
        Animated.timing(pulse, { toValue: 1, duration: 650, useNativeDriver: true }),
      ])).start();
    } else {
      pulse.stopAnimation();
      pulse.setValue(1);
    }
  }, [speaking, pulse]);

  const play = () => speak(phrase, slower, { onStart: () => setSpeaking(true), onDone: () => setSpeaking(false), onError: () => setSpeaking(false) });
  const toggleSlower = () => {
    const nextSlower = !slower;
    setSlower(nextSlower);
    speak(phrase, nextSlower, { onStart: () => setSpeaking(true), onDone: () => setSpeaking(false), onError: () => setSpeaking(false) });
  };

  return <SafeAreaView style={styles.safe}><View style={styles.content}>
    <ScreenHeader onBack={() => router.back()} action={<Pressable hitSlop={12}><Ionicons name="ellipsis-horizontal" size={25} color={colors.muted} /></Pressable>} />
    <View style={styles.phraseWrap}><Text adjustsFontSizeToFit numberOfLines={6} minimumFontScale={0.65} style={styles.phrase}>{phrase}</Text></View>
    <View style={styles.wave}>{[10, 21, 34, 18, 27, 12, 24, 10].map((height, index) => <View key={index} style={[styles.bar, { height: speaking ? height * 1.35 : height, opacity: speaking ? 1 : 0.35 }]} />)}</View>
    <Animated.View style={{ transform: [{ scale: pulse }] }}><Pressable accessibilityRole="button" accessibilityLabel={speaking ? 'Stop speaking' : 'Speak phrase'} onPress={speaking ? () => { stopSpeaking(); setSpeaking(false); } : play} style={styles.speakOuter}><LinearGradient colors={['#4F8CFF', '#245EF5']} style={styles.speakButton}><Ionicons name={speaking ? 'stop' : 'play'} size={48} color="white" style={!speaking ? { marginLeft: 6 } : undefined} /></LinearGradient></Pressable></Animated.View>
    <Text style={styles.status}>{speaking ? 'Speaking... Tap to stop' : 'Tap to speak'}</Text>
    <View style={styles.actions}><Action icon="speedometer-outline" label="Slower" active={slower} onPress={toggleSlower} /><Action icon="refresh" label="Repeat" onPress={play} /><Action icon={favorite ? 'heart' : 'heart-outline'} label="Favorite" active={favorite} onPress={() => setFavorite(!favorite)} /></View>
    <Text style={styles.disclosure}>{"Voice is generated by your device's text-to-speech system."}</Text>
  </View></SafeAreaView>;
}

function Action({ icon, label, onPress, active }: { icon: keyof typeof Ionicons.glyphMap; label: string; onPress: () => void; active?: boolean }) {
  return <Pressable accessibilityRole="button" accessibilityState={{ selected: active }} onPress={onPress} style={styles.action}><View style={[styles.actionIcon, active && styles.actionActive]}><Ionicons name={icon} size={26} color={active ? '#2867FA' : colors.muted} /></View><Text style={[styles.actionText, active && { color: '#2867FA' }]}>{label}</Text></Pressable>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { flex: 1, padding: 22, alignItems: 'center' }, phraseWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 }, phrase: { fontFamily: 'Jakarta-ExtraBold', fontSize: 38, lineHeight: 49, color: colors.text, textAlign: 'center', letterSpacing: -1.2 }, wave: { height: 48, flexDirection: 'row', alignItems: 'center', gap: 8 }, bar: { width: 4, borderRadius: 3, backgroundColor: colors.primary }, speakOuter: { width: 132, height: 132, borderRadius: 66, padding: 10, backgroundColor: '#E7F0FF', ...shadow }, speakButton: { flex: 1, borderRadius: 60, alignItems: 'center', justifyContent: 'center' }, status: { fontFamily: 'Jakarta-Medium', fontSize: 13, color: colors.muted, marginTop: 15 }, actions: { width: '100%', flexDirection: 'row', justifyContent: 'space-around', marginTop: 35 }, action: { alignItems: 'center', gap: 7, minWidth: 82 }, actionIcon: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, actionActive: { backgroundColor: '#EDF4FF', borderColor: colors.primary }, actionText: { fontFamily: 'Jakarta-Medium', fontSize: 12, color: colors.muted }, disclosure: { fontFamily: 'Jakarta-Regular', fontSize: 10, color: '#94A3B8', marginTop: 28, textAlign: 'center' } });
